---
# tasks file for python

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
   - python
   - python-pip

- name: Install python dependencies
  pip:
    name: "{{ item.name }}"
    state: present
    version: "{{ item.version }}"
  with_items:
   - {name: ystockquote, version: 0.2.0}
